$env:KAFKA_TO_SIGNALR_RELAY_KAFKA_BOOTSTRAP_SERVERS="localhost:9092"
$env:KAFKA_TO_SIGNALR_RELAY_KAFKA_GROUP_ID="harald-consumer"
$env:KAFKA_TO_SIGNALR_RELAY_KAFKA_ENABLE_AUTO_COMMIT="false"
dotnet watch --project ..\src\KafkaToSignalrRelay run
$env:KAFKA_TO_SIGNALR_RELAY_KAFKA_BOOTSTRAP_SERVERS=""
$env:KAFKA_TO_SIGNALR_RELAY_KAFKA_GROUP_ID=""
$env:KAFKA_TO_SIGNALR_RELAY_KAFKA_ENABLE_AUTO_COMMIT=""